export const headerStyles = {
    appHeaderBar: {
    width: '100%',
    height: '80px',
    background: '#FFF',
    borderBottom: '1px solid #EDEDED',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    position: 'fixed',
    top: 0, 
    left: 0, 
    right: 0, 
    zIndex: 999, 
    },

    logo: {
        width: '20%',
    },

    weatherInfoBar: {
        width: '100%',
        height: '70px',
        background: '#FFF',
        borderBottom: '1px solid #EDEDED',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        position: 'absolute',
        top: 80, 
        left: 0, 
        right: 0, 
        zIndex: 500,
    },

    breadCrumbs: {
        width: '100%',
        height: '50px',
        background: '#FFF',
        borderBottom: '1px solid #EDEDED',
        display: 'flex',
        alignItems: 'center',
        position: 'absolute',
        justifyContent: 'space-between',
        top: 80, 
        left: 0, 
        right: 0, 
        zIndex: 500,
    },
}   